# Generated by Django 6.0.1 on 2026-04-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parcinfo', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.departement'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipement',
            name='etat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Parcinfo.etat'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='type_equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcinfo.typeequipement'),
        ),
    ]
