# Generated by Django 6.0.1 on 2026-04-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parcinfo', '0002_initial'),
        ('interventions', '0002_initial'),
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='equipement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Parcinfo.equipement'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.typeintervention'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket'),
        ),
    ]
